# -*- coding: utf-8 -*-
"""Proyecto_Siniestros_Grupo1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Dr8_uPRkHVOBNscmH6p8YinckKYtIbmp

#Importaciones de librerias
"""

import matplotlib.pyplot as plt
import numpy as np
import seaborn as sns
import pandas as pd
import geopandas as gpd
from shapely.geometry import Point
import matplotlib.pyplot as plt
import folium

"""#Llamado al dataset"""

df = pd.read_excel("/content/DataSet_Siniestros_Guayaquil_Grupo1.xlsx")
df.head()

df.info()

"""El dataframe no continene valores nulos. A continuación se definiran las variables categoricas."""

#Categorizamos los datos e indicamos si son strings
df["PROVINCIA"] = df["PROVINCIA"].str.capitalize().astype("string")
df["CANTON"] = df["CANTON"].str.capitalize().astype("string")
df["PARROQUIA"] = df["PARROQUIA"].str.capitalize().astype("string")
df["DIRECCION"] = df["DIRECCION"].str.capitalize().astype("string")
df["ZONA"] = df["ZONA"].str.capitalize().astype("string")
df["CAUSA_PROBABLE"] = df["CAUSA_PROBABLE"].str.capitalize().astype("category")
df["EDAD"] = df["EDAD"].astype("category")
df["TIPO_DE_VEHICULO"] = df["TIPO_DE_VEHICULO"].str.capitalize().astype("category")

#Cambiamos los valores de Yes y No a valores de True y False
df['CASCO'] = df['CASCO'].replace({'SI': True, 'NO': False})
df['CINTURON'] = df['CINTURON'].replace({'SI': True, 'NO': False})
df['FERIADO'] = df['FERIADO'].replace({'SI': True, 'NO': False})

#En las edades existe el valor -1 el cual se cambiara al valor "Edad desconocida"
df['EDAD'] = df['EDAD'].replace(-1, "Edad Desconocida")

#Se arma el geodataframe para un analisis posterior
gdf = gpd.GeoDataFrame(
    df, geometry=gpd.points_from_xy(df.LONGITUD_X, df.LATITUD_Y))

"""##Geodata frame"""

# Cargar los datos geográficos de las zonas
zonas_gdf = gpd.read_file("zonas_inec.geojson")

# Asegurarse de que ambos conjuntos de datos tengan el mismo CRS
gdf = gpd.GeoDataFrame(
    df, geometry=gpd.points_from_xy(df.LONGITUD_X, df.LATITUD_Y)).set_crs(epsg=4326)
zonas_gdf = zonas_gdf.to_crs(epsg=4326)

# Realizar una unión espacial entre los datos de accidentes y las zonas geográficas
accidentes_por_zona_gdf = gpd.sjoin(gdf, zonas_gdf, how="left", predicate="within")

# Contar el número de accidentes por zona
accidentes_por_zona = accidentes_por_zona_gdf.groupby('DPA_ZONA').size().reset_index(name='NUM_ACCIDENTES')

# Unir los resultados con el GeoDataFrame de zonas
zonas_gdf = zonas_gdf.merge(accidentes_por_zona, how='left', on='DPA_ZONA', suffixes=('', '_y'))

# Eliminar la columna duplicada si existe
if 'NUM_ACCIDENTES_y' in zonas_gdf.columns:
    zonas_gdf = zonas_gdf.drop(columns='NUM_ACCIDENTES_y')

# Crear un mapa interactivo con Folium
m = folium.Map(location=[-1.8312, -78.1834], zoom_start=7)  # Centrar el mapa en Ecuador

# Añadir la capa de accidentes por zona utilizando Choropleth
choropleth = folium.Choropleth(
    geo_data=zonas_gdf,
    name='choropleth',
    data=zonas_gdf,
    columns=['DPA_ZONA', 'NUM_ACCIDENTES'],
    key_on='feature.properties.DPA_ZONA',
    fill_color='YlGnBu',
    fill_opacity=0.7,
    line_opacity=0.2,
    line_color='black',  # Agregar contornos
    line_weight=1,       # Grosor de los contornos
    legend_name='Número de accidentes por zona'
).add_to(m)

# Añadir información interactiva con GeoJson
folium.GeoJson(
    zonas_gdf,
    style_function=lambda x: {
        'fillColor': '#00000000',  # Sin color de relleno
        'color': 'black',
        'weight': 1,
        'fillOpacity': 0.7,
        'lineOpacity': 0.2
    },
    tooltip=folium.GeoJsonTooltip(
        fields=['DPA_ZONA', 'NUM_ACCIDENTES'],
        aliases=['Zona:', 'Número de Accidentes:'],
        localize=True
    )
).add_to(m)

# Guardar el mapa como un archivo HTML
m.save('mapa_accidentes_folium.html')

"""#Limpieza de Datos

## Reclasificación de columnas

En base a tipos de vehiculo se creara una categoria donde se clasifique el tipo de conducto, ya sea profesional, particular u otros.
*  **Particulares:** Automovil, Motocicleta, Vehiculo deportivo utilitario, Camioneta
*  **Profesionales**: Bus, Camion, Furgoneta
*  **No identificados:** No identificado
*  **Especiales:** Especial, Bicicleta, Tricimoto, Scooter electrico, Emergencias
"""

TIPO_DE_CONDUCTOR_MAPPING = {
    'Automovil': 'Vehículos Particulares',
    'Motocicleta': 'Vehículos de Movilidad Personal',
    'Vehiculo deportivo utilitario': 'Vehículos Particulares',
    'Camioneta': 'Vehículos Particulares',
    'Bus': 'Vehículos de Transporte Público',
    'Camion': 'Vehículos de Carga',
    'Furgoneta': 'Vehículos de Transporte Público',
    'No identificado': 'Vehículos No Identificados',
    'Especial': 'Vehículos de Emergenica y Servicios Especiales',
    'Bicicleta': 'Vehículos de Movilidad Personal',
    'Tricimoto': 'Vehículos de Movilidad Personal',
    'Scooter electrico': 'Vehículos de Movilidad Personal',
    'Emergencias': 'Vehículos de Emergenica y Servicios Especiales'
}
df['TIPO_DE_CONDUCTOR'] = df['TIPO_DE_VEHICULO'].map(TIPO_DE_CONDUCTOR_MAPPING)
df.head()

"""En base a edad se creará una categoria donde se clasifique el grupo de edad de los siniestros. Se tomara las siguientes categorias como referencia https://economipedia.com/definiciones/segmentacion-por-edad.html

"""

# Define a function to categorize ages
def categorize_age(age):
    if age == "Edad Desconocida":
        return "Edad no registrada"
    elif age < 18:
        return "Menor de edad"
    elif 18 <= age <= 24:
        return "Joven"
    elif 25 <= age <= 39:
        return "Adulto joven"
    elif 40 <= age <= 54:
        return "Adulto"
    elif 55 <= age <= 64:
        return "Adulto mayor"
    elif age >= 65:
        return "Tercera edad"

# Apply the function to the EDAD column to create a new column CATEGORIA_EDAD
df['CATEGORIA_EDAD'] = df['EDAD'].apply(categorize_age)
df.head()

"""## Categorizacion y Subcategorizacion de las causas probables

Para las causas probables se empleara el archivo Data-causaAccidentes que categoriza las Causa_probable y tambien la subcategoriza
"""

df_causas = pd.read_excel("/content/Data-CausasAccidentes.xlsx")
df_causas["CAUSA_PROBABLE"] = df_causas["CAUSA_PROBABLE"].str.capitalize().astype("category")
df_causas.head()

merged_df = pd.merge(df, df_causas, how='left', on='CAUSA_PROBABLE')
merged_df.head()

"""##Eliminación de filas no necesarias

Dentro del database se observa parroquias que si bien son parte del canton de Guayaquil, para motivos del analisis se basara netamente en la parroquia urbana Guayaquil.
"""

df_guayaquil = merged_df.loc[df["PARROQUIA"] == "Guayaquil"]
df_guayaquil

"""##Exportamos la nueva tabla"""

df_guayaquil.to_excel("Siniestros_Limpio_G1.xlsx", index=False)

"""# Preguntas de Negocio

## ¿Cuál es la tasa actual de accidentes de tráfico en Guayaquil?

Segun los resultados del ultimo censo en 2023 guayaquil tiene 2,746,403 habitantes (https://www.ecuavisa.com/noticias/ecuador/las-ciudades-mas-pobladas-de-ecuador-2023-resultados-censo-BE6006267#:~:text=Seg%C3%BAn%20los%20resultados%20del%20%C3%BAltimo,2%20746%20403%20de%20habitantes.)
"""

ultimo_anio = 2023
df_ultimo_anio = df_guayaquil[df_guayaquil['ANIO'] == ultimo_anio]

num_accidentes_ultimo_anio = df_ultimo_anio.shape[0]
poblacion_guayaquil = 2746403
tasa_accidentes = (num_accidentes_ultimo_anio / poblacion_guayaquil) * 100000

tasa_accidentes

df_fatales = df_guayaquil[(df_guayaquil['ANIO'] == ultimo_anio) & (df_guayaquil['CONDICION'] == 'FALLECIDO')]
num_mortales_ultimo_anio = df_fatales.shape[0]
poblacion_guayaquil = 2746403
tasa_mortalidad = (num_mortales_ultimo_anio / poblacion_guayaquil) * 100000
tasa_mortalidad

"""## ¿Cuál es la tendencial de la siniestralidad vial en los últimos cinco años?"""

# Agrupar por año y contar el número de accidentes
accidentes_por_anio = df_guayaquil.groupby('ANIO').size()

# Graficar la tendencia
plt.figure(figsize=(10, 6))
accidentes_por_anio.plot(kind='bar', color='skyblue')
plt.title('Tendencia de Accidentes de Tráfico en los Últimos Cinco Años')
plt.xlabel('Año')
plt.ylabel('Número de Accidentes')
plt.show()

plt.figure(figsize=(10, 6))
year_counts = df_guayaquil['ANIO'].value_counts().sort_index()
sns.lineplot(x=year_counts.index, y=year_counts.values, marker='o')
plt.title('Tendencia de Accidentes a lo Largo de los Años')
plt.xlabel('Año')
plt.ylabel('Número de Accidentes')
plt.show()

"""## ¿Cuáles son las áreas de la ciudad con mayor incidencia de accidentes de transito? ¿Existe alguna relación entre la ubicación geográfica y la frecuencia de accidentes?"""

# Cargar los datos geográficos de las zonas
zonas_gdf = gpd.read_file("zonas_inec.geojson")

# Asegurarse de que ambos conjuntos de datos tengan el mismo CRS
gdf = gpd.GeoDataFrame(
    df, geometry=gpd.points_from_xy(df.LONGITUD_X, df.LATITUD_Y)).set_crs(epsg=4326)
zonas_gdf = zonas_gdf.to_crs(epsg=4326)

# Realizar una unión espacial entre los datos de accidentes y las zonas geográficas
accidentes_por_zona_gdf = gpd.sjoin(gdf, zonas_gdf, how="left", predicate="within")

# Contar el número de accidentes por zona
accidentes_por_zona = accidentes_por_zona_gdf.groupby('DPA_ZONA').size().reset_index(name='NUM_ACCIDENTES')

# Unir los resultados con el GeoDataFrame de zonas
zonas_gdf = zonas_gdf.merge(accidentes_por_zona, how='left', on='DPA_ZONA', suffixes=('', '_y'))

# Eliminar la columna duplicada si existe
if 'NUM_ACCIDENTES_y' in zonas_gdf.columns:
    zonas_gdf = zonas_gdf.drop(columns='NUM_ACCIDENTES_y')

# Crear un mapa interactivo con Folium
m = folium.Map(location=[-1.8312, -78.1834], zoom_start=7)  # Centrar el mapa en Ecuador

# Añadir la capa de accidentes por zona utilizando Choropleth
choropleth = folium.Choropleth(
    geo_data=zonas_gdf,
    name='choropleth',
    data=zonas_gdf,
    columns=['DPA_ZONA', 'NUM_ACCIDENTES'],
    key_on='feature.properties.DPA_ZONA',
    fill_color='YlGnBu',
    fill_opacity=0.7,
    line_opacity=0.2,
    line_color='black',  # Agregar contornos
    line_weight=1,       # Grosor de los contornos
    legend_name='Número de accidentes por zona'
).add_to(m)

# Añadir información interactiva con GeoJson
folium.GeoJson(
    zonas_gdf,
    style_function=lambda x: {
        'fillColor': '#00000000',  # Sin color de relleno
        'color': 'black',
        'weight': 1,
        'fillOpacity': 0.7,
        'lineOpacity': 0.2
    },
    tooltip=folium.GeoJsonTooltip(
        fields=['DPA_ZONA', 'NUM_ACCIDENTES'],
        aliases=['Zona:', 'Número de Accidentes:'],
        localize=True
    )
).add_to(m)

# Guardar el mapa como un archivo HTML
m.save('mapa_accidentes_folium.html')

"""## ¿Cuáles son los principales causales de los accidentes de tráfico en Guayaquil?"""

causas_accidentes = df_guayaquil['Categoría'].value_counts().head(10)

# Graficar las principales causas
plt.figure(figsize=(10, 6))
causas_accidentes.plot(kind='bar', color='orange')
plt.title('Principales Categorías de Accidentes de Tráfico')
plt.xticks(rotation=45, ha='right')
plt.show()

categoria_errores_cond = df_guayaquil.loc[df_guayaquil['Categoría'] == "Errores del Conductor"]
causas_accidentes = categoria_errores_cond['Subcategoría'].value_counts().head(10)

# Graficar las principales causas
plt.figure(figsize=(10, 6))
causas_accidentes.plot(kind='bar', color='orange')
plt.title('Subcategorias de Errores del Conductor')
plt.xticks(rotation=45, ha='right')
plt.show()

"""## ¿Quiénes son los grupos más afectados por los accidentes?"""

# Contar la frecuencia de edades y sexos de los lesionados y fallecidos
df_filtro = df_guayaquil.loc[df_guayaquil['CATEGORIA_EDAD']!= "Edad no registrada"]
grupos_afectados = df_filtro[df_filtro['CONDICION'].isin(['LESIONADO', 'FALLECIDO'])]['CATEGORIA_EDAD'].value_counts().head(10)

# Graficar los grupos más afectados
plt.figure(figsize=(10, 6))
grupos_afectados.plot(kind='bar', color='green')
plt.title('Grupos Más Afectados por Edad')
plt.xticks(rotation=45, ha='right')
plt.show()

# Gráfico de Pastel: Distribución de accidentes por ZONA
plt.figure(figsize=(8, 8))
zona_counts = df_guayaquil['SEXO'].value_counts()
plt.pie(zona_counts, labels=zona_counts.index, autopct='%1.1f%%', startangle=140)
plt.title('Distribución de Accidentes por Genero')
plt.show()

df_filtro = df_guayaquil.loc[df_guayaquil['CATEGORIA_EDAD'] != "Edad no registrada"]
df_filtro = df_filtro[df_filtro['CONDICION'].isin(['LESIONADO', 'FALLECIDO'])]
grupos_afectados = df_filtro.groupby(['CATEGORIA_EDAD', 'SEXO']).size().unstack(fill_value=0)

grupos_afectados['Total'] = grupos_afectados.sum(axis=1)
top_10_edades = grupos_afectados.nlargest(10, 'Total').index
grupos_afectados_top = grupos_afectados.loc[top_10_edades].sort_values(by='Total', ascending=False)

fig, ax = plt.subplots(figsize=(14, 8))
colors = ['#EDC45B','#4E4E4E']
grupos_afectados_top.drop(columns='Total').plot(kind='bar', stacked=True, color=colors, ax=ax)

ax.set_title('Grupos Más Afectados por Edad y Género', fontsize=16)
ax.set_xlabel(None)
ax.set_ylabel(None)
ax.set_xticklabels(grupos_afectados_top.index, rotation=45, ha='right', fontsize=12)
ax.legend(title='Género', fontsize=12, title_fontsize=14)

for i, age in enumerate(grupos_afectados_top.index):
    hombres = grupos_afectados_top.loc[age, 'HOMBRE']
    mujeres = grupos_afectados_top.loc[age, 'MUJER']
    total = hombres + mujeres

    ax.text(i, hombres / 2, str(hombres), ha='center', va='center', color='white', fontsize=12)
    ax.text(i, hombres + mujeres / 2, str(mujeres), ha='center', va='center', color='white', fontsize=12)
    ax.text(i, total + 0.5, str(total), ha='center', va='bottom', fontsize=12, fontweight='bold')

plt.tight_layout()
plt.show()

"""## ¿Cuál es el impacto de los dispositivos de seguridad?"""

def uso_dispositivos_seguridad(row):
    if row['CASCO'] or row['CINTURON']:
        return True
    else:
      return False
df_seguridad = df_guayaquil.copy()
df_seguridad['USO_DISPOSITIVOS_SEGURIDAD'] = df_seguridad.apply(uso_dispositivos_seguridad, axis=1)

plt.figure(figsize=(14, 7))
sns.countplot(data=df_seguridad, x='ANIO', hue='USO_DISPOSITIVOS_SEGURIDAD', palette='viridis')
plt.title('Distribución del uso de dispositivo de seguridad por año')
plt.legend(title='Uso dispositivo de seguridad', labels=['No', 'Sí'])
plt.xticks(rotation=45)
plt.xlabel(None)
plt.ylabel(None)
plt.show()

df_fallecido_lesiones = df_seguridad.loc[(df_seguridad['CONDICION'] == 'LESIONADO') | (['CONDICION'] == 'FALLECIDO')]
df_solo_ileso = df_seguridad.loc[df_seguridad['CONDICION'] == 'ILESO']

fig, axes = plt.subplots(2, 1, figsize=(14, 14))

sns.countplot(data=df_fallecido_lesiones, x='ANIO', hue='USO_DISPOSITIVOS_SEGURIDAD', palette=['#4E4E4E', '#EDC45B'], ax=axes[0])
axes[0].set_title('Siniestros con Lesiones/Fallecimientos por Año', size = 35)
axes[0].legend(title='Uso dispositivo de seguridad', labels=['No', 'Sí'])
axes[0].set_xlabel(None)
axes[0].set_ylabel(None)
axes[0].tick_params(axis='x', rotation=45)

sns.countplot(data=df_solo_ileso, x='ANIO', hue='USO_DISPOSITIVOS_SEGURIDAD', palette=['#4E4E4E', '#EDC45B'], ax=axes[1])
axes[1].set_title('Siniestros Ilesos por Año', size = 35)
axes[1].legend(title='Uso dispositivo de seguridad', labels=['No', 'Sí'])
axes[1].set_xlabel(None)
axes[1].set_ylabel(None)
axes[1].tick_params(axis='x', rotation=45)

plt.tight_layout()
plt.show()